In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('../data/processed/02_cleaning.csv')

print(df)

     Serial_No                   Name   Type_1  Type_2  Total  HP  Attack  \
0            1              Bulbasaur    Grass  Poison    318  45      49
1            2                Ivysaur    Grass  Poison    405  60      62
2            3               Venusaur    Grass  Poison    525  80      82
3            3  VenusaurMega Venusaur    Grass  Poison    625  80     100
4            4             Charmander     Fire     NaN    309  39      52
..         ...                    ...      ...     ...    ...  ..     ...
795        719                Diancie     Rock   Fairy    600  50     100
796        719    DiancieMega Diancie     Rock   Fairy    700  50     160
797        720    HoopaHoopa Confined  Psychic   Ghost    600  80     110
798        720     HoopaHoopa Unbound  Psychic    Dark    680  80     160
799        721              Volcanion     Fire   Water    600  80     110

     Defense  Sp_Atk  Sp_Def  Speed  Generation  Legendary
0         49      65      65     45           1      False
1         63      80      80     60           1      False
2         83     100     100     80           1      False
3        123     122     120     80           1      False
4         43      60      50     65           1      False
..       ...     ...     ...    ...         ...        ...
795      150     100     150     50           6       True
796      110     160     110    110           6       True
797       60     150     130     70           6       True
798       60     170     130     80           6       True
799      120     130      90     70           6       True

[800 rows x 13 columns]

In [39]:

type_avg_total = (
    df.groupby('Type_1')['Total'].mean().sort_values(ascending = False)
)

print(type_avg_total)

type_avg_total.to_csv('../data/processed/Type_avg_total.csv', index = False)

Type_1
Dragon      550.531250
Steel       487.703704
Flying      485.000000
Psychic     475.947368
Fire        458.076923
Rock        453.750000
Dark        445.741935
Electric    443.409091
Ghost       439.562500
Ground      437.500000
Ice         433.458333
Water       430.455357
Grass       421.142857
Fighting    416.444444
Fairy       413.176471
Normal      401.683673
Poison      399.142857
Bug         378.927536
Name: Total, dtype: float64

In [40]:
avg_attack_type = (
    df.groupby('Type_1')['Attack'].mean().sort_values(ascending = False)
)

print(avg_attack_type)

avg_attack_type.to_csv('../data/processed/Avg_attack_type.csv', index = False)

Type_1
Dragon      112.125000
Fighting     96.777778
Ground       95.750000
Rock         92.863636
Steel        92.703704
Dark         88.387097
Fire         84.769231
Flying       78.750000
Poison       74.678571
Water        74.151786
Ghost        73.781250
Normal       73.469388
Grass        73.214286
Ice          72.750000
Psychic      71.456140
Bug          70.971014
Electric     69.090909
Fairy        61.529412
Name: Attack, dtype: float64

In [41]:
avg_defense_type = (
    df.groupby('Type_1')['Defense'].mean().sort_values(ascending = False)
)

print(avg_defense_type)

avg_defense_type.to_csv('../data/processed/Avg_defense_type.csv', index = False)

Type_1
Steel       126.370370
Rock        100.795455
Dragon       86.375000
Ground       84.843750
Ghost        81.187500
Water        72.946429
Ice          71.416667
Grass        70.800000
Bug          70.724638
Dark         70.225806
Poison       68.821429
Fire         67.769231
Psychic      67.684211
Electric     66.295455
Flying       66.250000
Fighting     65.925926
Fairy        65.705882
Normal       59.846939
Name: Defense, dtype: float64

In [42]:
legendary_comparison = (
    df.groupby("Legendary")["Total"]
      .mean()
)

print(legendary_comparison)

legendary_comparison.to_csv('../data/processed/Legendary_comparison.csv', index = False)

Legendary
False    417.213605
True     637.384615
Name: Total, dtype: float64

In [43]:
generation_avg_total = (
    df.groupby('Generation')['Total'].mean().sort_values(ascending = False)
)

print(generation_avg_total)

generation_avg_total.to_csv('../data/processed/Generation_avg_total.csv', index = False)

Generation
4    459.016529
6    436.378049
3    436.225000
5    434.987879
1    426.813253
2    418.283019
Name: Total, dtype: float64

Key Findings

- Dragon type has the highest average Attack.

- Steel type has the highest average Defense.

- Dragon, Steel, and Flying rank highest by average Total.

- Legendary Pokémon have significantly higher average Total stats than non-legendary Pokémon.

- No consistent increase in average Total stats across generations.

In [44]:
df = pd.read_csv('../data/processed/Feature_enginnered.csv')

In [45]:
df.pivot_table(
    values=["Attack", "Defense", "Speed"],
    index="Type_1",
    aggfunc="mean"
)

              Attack     Defense       Speed
Type_1
Bug        70.971014   70.724638   61.681159
Dark       88.387097   70.225806   76.161290
Dragon    112.125000   86.375000   83.031250
Electric   69.090909   66.295455   84.500000
Fairy      61.529412   65.705882   48.588235
Fighting   96.777778   65.925926   66.074074
Fire       84.769231   67.769231   74.442308
Flying     78.750000   66.250000  102.500000
Ghost      73.781250   81.187500   64.343750
Grass      73.214286   70.800000   61.928571
Ground     95.750000   84.843750   63.906250
Ice        72.750000   71.416667   63.458333
Normal     73.469388   59.846939   71.551020
Poison     74.678571   68.821429   63.571429
Psychic    71.456140   67.684211   81.491228
Rock       92.863636  100.795455   55.909091
Steel      92.703704  126.370370   55.259259
Water      74.151786   72.946429   65.964286

In [46]:
df.pivot_table(
    values=["Offensive_Power", "Defensive_Power"],
    index="Type_1",
    aggfunc="mean"
).sort_values("Offensive_Power", ascending=False)

          Defensive_Power  Offensive_Power
Type_1
Dragon         175.218750       208.968750
Fire           139.980769       173.750000
Flying         138.750000       173.000000
Psychic        153.964912       169.859649
Dark           139.741935       163.032258
Steel          207.000000       160.222222
Electric       140.000000       159.113636
Rock           176.272727       156.204545
Ghost          157.656250       153.125000
Ground         147.593750       152.218750
Grass          141.228571       150.714286
Ice            147.708333       150.291667
Fighting       130.629630       149.888889
Water          143.464286       148.964286
Fairy          150.411765       140.058824
Poison         133.214286       135.107143
Normal         123.571429       129.285714
Bug            135.521739       124.840580

In [47]:
df.pivot_table(
    values="Total",
    index="Generation",
    aggfunc="mean"
)

                 Total
Generation
1           426.813253
2           418.283019
3           436.225000
4           459.016529
5           434.987879
6           436.378049